# Generated by Django 3.1.2 on 2020-10-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('week3', '0002_auto_20201027_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='author_profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='week3.profile'),
        ),
    ]
